---

plugins:
    - babel

env:
    node: true

parser: babel-eslint

extends:
    - 'airbnb-base'

rules:
    no-console: 0
    indent: [ "error", 4 ]
    no-param-reassign: [ "error", { "props": false } ]
    import/prefer-default-export: 0
